.\" # Copyright 2009-2022 David Robillard <d@drobilla.net>
.\" # SPDX-License-Identifier: ISC
.Dd Nov 29, 2022
.Dt LV2INFO 1
.Os Lilv 0.25.1
.Sh NAME
.Nm lv2info
.Nd print information about an installed LV2 plugin
.Sh SYNOPSIS
.Nm lv2info
.Op Fl hV
.Op Fl m Ar file
.Op Fl p Ar file
.Ar plugin_uri
.Sh DESCRIPTION
.Nm
prints a human-readable summary of information about an LV2 plugin.
.Pp
The plugin must be installed;
.Nm
will search for one with the given
.Ar plugin_uri
in the LV2 path.
.Pp
The options are as follows:
.Pp
.Bl -tag -compact -width 3n
.It Fl V , Fl Fl version
Display version information and exit.
.Pp
.It Fl h , Fl Fl help
Print the command line options.
.Pp
.It Fl m Ar file
Add record of plugin to Turtle manifest
.Ar file .
.Pp
.It Fl p Ar file
Write description of plugin to Turtle
.Ar file .
.El
.Sh ENVIRONMENT
.Bl -tag -width LV2_PATH -compact
.It Ev LV2_PATH
List of directories to search for LV2 plugin bundles,
in the style of
.Ev PATH .
.El
.Sh EXIT STATUS
.Nm
exits with a status of 0, or non-zero if an error occurred.
.Sh SEE ALSO
.Bl -item -compact
.It
.Xr lv2apply 1
.It
.Xr lv2bench 1
.It
.Xr lv2ls 1
.El
.Sh AUTHORS
.Nm
is a part of lilv, by
.An David Robillard
.Mt d@drobilla.net .
